name: Unity Test

on:
  push:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - uses: game-ci/unity-test-runner@v2
        id: unitytest
        with:
          testMode: editmode
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          customParameters: -enableCodeCoverage
      - uses: actions/upload-artifact@v2
        with:
          name: TestResults
          path: ./CodeCoverage